name = "cake_sqlight"
version = "1.0.3"
description = "ğŸ‚Cake ğŸª¶SQLite adapter which passes PreparedStatements to the sqlight library for execution written in Gleam."
licences = ["MPL-2.0"]
repository = { type = "github", user = "inoas", repo = "gleam-cake-sqlight" }
# links = [{ title = "Website", href = "https://gleam.run" }]

gleam = ">= 1.4.0 and < 2.0.0"
dev-dependencies = { gleeunit = ">= 1.2.0 and < 2.0.0", pprint = ">= 1.0.4 and < 2.0.0", birdie = ">= 1.2.3 and < 2.0.0" }

[documentation]
pages = [
    { title = "CHANGELOG", path = "changelog.html", source = "CHANGELOG.md" },
]

[dependencies]
cake = ">= 2.0.0 and < 3.0.0"
gleam_stdlib = ">= 0.40.0 and < 2.0.0"
sqlight = ">= 0.9.1 and < 2.0.0"
