name = "cake_sqlight"
version = "1.1.1"
description = "ğŸ‚Cake ğŸª¶SQLite adapter which passes PreparedStatements to the sqlight library for execution written in Gleam."
licences = ["MPL-2.0"]
repository = { type = "github", user = "inoas", repo = "gleam-cake-sqlight" }
# links = [{ title = "Website", href = "https://gleam.run" }]

gleam = ">= 1.6.0"

[documentation]
pages = [
    { title = "CHANGELOG", path = "changelog.html", source = "CHANGELOG.md" },
]

[dependencies]
cake = ">= 2.0.0 and < 3.0.0"
gleam_stdlib = ">= 0.50.0 and <= 2.0.0"
sqlight = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
birdie = ">= 1.2.5 and < 2.0.0"
gleeunit = ">= 1.2.0 and < 2.0.0"
pprint = ">= 1.0.4 and < 2.0.0"
